version: "3"

services:
  gim-es:
    container_name: gim-es
    hostname: gim-es
    image: elastic/elasticsearch:7.17.6
    restart: always
    user: root
    ports:
      - 9200:9200
    networks:
      gim-network:
        ipv4_address: "192.168.9.110"
    volumes:
      - ./configs/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Volumes/data/gim/elasticsearch/data:/usr/share/elasticsearch/data
      - /Volumes/data/gim/elasticsearch/logs:/usr/share/elasticsearch/logs
    privileged: true
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "TAKE_FILE_OWNERSHIP=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Asia/Shanghai"
      - "ELASTIC_PASSWORD=lark2022"

  gim-kibana:
    container_name: gim-kibana
    hostname: gim-kibana
    image: elastic/kibana:7.17.6
    restart: always
    ports:
      - 5601:5601
    networks:
      gim-network:
        ipv4_address: "192.168.9.120"
    volumes:
      - ./configs/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    privileged: true
    environment:
      - elasticsearch.hosts=http://gim-es:9200
      - "TZ=Asia/Shanghai"
    depends_on:
      - gim-es

  gim-logstash:
    container_name: gim-logstash
    hostname: gim-logstash
    image: logstash:7.17.6
    restart: always
    ports:
      - 7701:7701
#      - 7702:7702
#      - 7703:7703
      - 5044:5044
#      - 9600:9600
    networks:
      gim-network:
        ipv4_address: "192.168.9.130"
    volumes:
      - ./configs/docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      #- /Volumes/data/gim/logstash/logs:/usr/share/logstash/logs
      - ./configs/docker/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      #- ./configs/docker/logstash/certs:/usr/share/logstash/config/certs
    privileged: true
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOSTS: http://gim-es:9200
    depends_on:
      - gim-es

  gim-filebeat:
    container_name: gim-filebeat
    hostname: gim-filebeat
    image: elastic/filebeat:7.17.6
    restart: always
    networks:
      gim-network:
        ipv4_address: "192.168.9.131"
    volumes:
      - ./configs/docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/gim:/usr/share/filebeat/logs
      #- ./configs/docker/filebeat/certs:/etc/filebeat/config/certs
      #- /Volumes/data/gim/filebeat/containers:/var/lib/docker/containers:ro
      #- /Volumes/data/gim/filebeat/docker.sock:/var/run/docker.sock:ro
    privileged: true
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOSTS: http://gim-es:9200
    depends_on:
      - gim-logstash
      - gim-kibana

networks:
  gim-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/24
          ip_range: 192.168.9.0/24